# Project Information
site_name: Dymaxion
site_url: https://www.dymaxion.world/
site_description: Unit Geometry Library
site_author: Geoid
base_url: https://www.dymaxion.world/

# Repository
repo_name: 'GitHub'
repo_url: https://github.com/geoid-org/dymaxion/
edit_uri_template: 'docs/{path}'

lang: en

dev_addr: 127.0.0.1:8888

plugins:
  - search:
      lang: en
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - mkdocstrings

# Configuration
theme:
  name: material
  custom_dir: 'docs/overrides'
  locale: en
  language: en
  palette:
    scheme: geoid
    # primary: 'indigo'
    # accent: 'red'
  # font:
  #   text: 'Manrope'
  #   code: 'Roboto Mono'
  logo: assets/image/logo_light.png
  favicon: assets/favicon/favicon.ico
  features:
  #   - navigation.tabs
  #   - navigation.tabs.sticky
    - navigation.expand
    - navigation.indexes
    - navigation.sections
    - navigation.footer
    - navigation.top
    # - navigation.instant
  #   - toc.integrate
    - toc.follow
    - navigation.tracking
    - search.highlight
    - search.suggest

# Customization
extra:
  generator: false
  analytics:
    provider: google
    property: G-6FEJJ20F68
  social:
    - icon: fontawesome/solid/globe 
      link: https://www.geoid.org
      name: Geoid Website
    - icon: fontawesome/brands/github 
      link: https://github.com/geoid-org
      name: Geoid GitHub
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/company/geoid-org
      name: Geoid LinkedIn
    - icon: fontawesome/brands/instagram 
      link: https://instagram.com/geoid_org
      name: Geoid Instagram
    - icon: fontawesome/brands/facebook 
      link: https://www.facebook.com/geoid.org
      name: Geoid Facebook
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
extra_css:
  - assets/style/extra.css
extra_javascript:
  - assets/script/extra.js
extra_templates:

# Copyright
copyright: >
  Copyright &copy; 2023 <a href="https://www.geoid.org">Geoid</a>. All Rights Reserved –
  <a href="#__consent">Change cookie settings</a>

# Extensions
# markdown_extensions:
#   - meta
#   - md_in_html
#   - toc:
#       permalink: true
#   - pymdownx.emoji:
#       emoji_index: !!python/name:materialx.emoji.twemoji
#       emoji_generator: !!python/name:materialx.emoji.to_svg

# hide:
#   - footer


nav:
  - Introduction: 'index.md'
  - Quick Start: 'quick_start.md'
  - Resources:
      - 'Glossary': 'resources/glossary.md'
      - 'Links': 'resources/links.md'
  - About:
      - 'Authors': 'about/authors.md'
  - Development:
      - 'Roadmap': 'development/roadmap.md'
      - 'Contributing': 'development/contributing.md'
      - 'Code of Conduct': 'development/code_of_conduct.md'
  - Legal Information:
      - 'License': 'legal/license.md'
      - 'Privacy Policy': 'legal/privacy_policy.md'
      - 'Disclaimer': 'legal/disclaimer.md'

